# [[[ BanOPExploiter ]]]
# Bans exploiters who got OP or admin perms.
# Блокирует хацкеров, которые получили опку или админку.

check-every-seconds: 10
allowed-players-list:
  - "NotHacker228"
  - "JustTimePlay_Bobik"

ban-if-have:
  op: true
  perms: true
  perms-list:
    - "*"
    - "worldedit.*"

ban-commands:
  - "deop %player%"
  - "lp user %player% permission unset *"
  - "lp user %player% permission unset worldedit.*"
  - "ban %player% Exploit"
  - "say %player% is exploiter because he just got %op-or-perm%"

when-plugin-disabled-command: "minecraft:kick @a Server is reloading, please rejoin" #to do nothing "nothing"